[build-system]
requires = ["setuptools", "wheel"]  # Build requirements
build-backend = "setuptools.build_meta"

[project]
name = "TravNet" 
version = "1.0.0"
description = "A Python package for TravNet, A car trip simulator."
readme = "ReadMe.md"
requires-python = ">=3.12"


# Runtime dependencies
dependencies = [
  "torch",
  "scikit-learn",
  "matplotlib",
  "numpy",
  "ipykernel",
  "pandas",
]

[tool.setuptools]
packages = ["Modules"] 